name: test optimus resources

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: test optimus resources
        working-directory: ext/scheduler/airflow2/tests/
        run: make test